### PR TITLE
Added ability to completely turn off tooltips

### PR DESCRIPTION
**Pull request by kgabor545**

### CODE REVIEW

**Comment by xuzhen** [comment]
I wouldn't understand the purpose of the changes. You hide the window list, not the tooltip.

**Comment by kgabor545** [comment]
Sorry if I am using the terms wrong. I don't want anything showing up on mouse hover. I was unable to achieve it without this modification. 
UPDATE: Yes it is window list sorry. I don't want window list even if more than one window. I will change the terms and make a new commit.

**Comment by xuzhen** [comment]
In my opinion, if there is a "not-show-window-list-on-hover" option, there also need be a "show-window-list" option in the ComboBoxes of Group button actions. Otherwise it's not easy to switch between multiple windows.

**Comment by kgabor545** [comment]
I use the mouse wheel to switch.

**Pull request closed without merging**
